COMPONENT_DEPENDS := \
	IFS \
	SPI

COMPONENT_SRCDIRS := \
	src

COMPONENT_INCDIRS := \
	src \
	src/include

COMPONENT_VARS			:= ENABLE_STORAGE_SIZE64
COMPONENT_RELINK_VARS	:= ENABLE_EXFAT
ifeq ($(ENABLE_EXFAT),1)
COMPONENT_CPPFLAGS		:= -DENABLE_EXFAT
endif
