COMPONENT_DEPENDS		:= DiskStorage IFS
COMPONENT_INCDIRS		:= src src/include
COMPONENT_SRCDIRS		:= src

COMPONENT_VARS			:= ENABLE_STORAGE_SIZE64 ENABLE_EXFAT
ifeq ($(ENABLE_EXFAT),1)
GLOBAL_CFLAGS			+= -DENABLE_EXFAT
endif


COMPONENT_VARS			+= ENABLE_FAT_TRIM
ifeq ($(ENABLE_FAT_TRIM),1)
COMPONENT_CPPFLAGS		+= -DENABLE_FAT_TRIM
endif


COMPONENT_VARS			+= FAT_CODEPAGE
FAT_CODEPAGE			?= 437
COMPONENT_CPPFLAGS		+= -DFAT_CODEPAGE=$(FAT_CODEPAGE)
